/*
 * Registry loader.
 *
 * Source priority:
 *   1. BOILA_REGISTRY env var (URL or local file path) — used by
 *      `pnpm --filter cli dev` against the in-repo registry.json.
 *   2. The default URL below.
 *
 * The registry is a static JSON file regenerated by
 * `scripts/build-registry.ts` on every web build. The CLI fetches it
 * once per invocation and never caches across runs (versions are tiny).
 *
 * Note: the default URL points at the Vercel deployment for now.
 * Swap to https://boila.dev/registry.json once the custom domain is
 * provisioned and DNS has propagated — that's the only code change
 * needed (no schema bump, the JSON shape stays identical).
 */
import { readFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { isAbsolute, resolve } from "node:path"

import type { Registry } from "./types.js"

/**
 * Production site URL — used both for fetching the registry and for
 * printing user-facing "Detail page" links after scaffold. Single
 * source of truth: bump once when you move to the custom domain.
 */
export const SITE_URL = "https://boila-web.vercel.app"

const DEFAULT_URL = `${SITE_URL}/registry.json`

export async function loadRegistry(): Promise<Registry> {
  const source = process.env.BOILA_REGISTRY?.trim() || DEFAULT_URL

  if (looksLikeUrl(source)) {
    return fetchRegistry(source)
  }

  // Local file (handy in dev): resolve relative to cwd.
  const path = isAbsolute(source) ? source : resolve(process.cwd(), source)
  if (!existsSync(path)) {
    throw new Error(
      `BOILA_REGISTRY points to "${source}" but the file does not exist.`
    )
  }
  const raw = await readFile(path, "utf8")
  return parseRegistry(raw, path)
}

async function fetchRegistry(url: string): Promise<Registry> {
  let res: Response
  try {
    res = await fetch(url, {
      headers: { accept: "application/json" },
    })
  } catch (err) {
    throw new Error(
      `Could not reach the registry at ${url}.\n  ${(err as Error).message}`
    )
  }
  if (!res.ok) {
    throw new Error(
      `Registry fetch failed: HTTP ${res.status} ${res.statusText} (${url})`
    )
  }
  const raw = await res.text()
  return parseRegistry(raw, url)
}

function parseRegistry(raw: string, source: string): Registry {
  let parsed: unknown
  try {
    parsed = JSON.parse(raw)
  } catch (err) {
    throw new Error(`Registry at ${source} is not valid JSON: ${(err as Error).message}`)
  }
  if (
    !parsed ||
    typeof parsed !== "object" ||
    !Array.isArray((parsed as Registry).boilerplates)
  ) {
    throw new Error(`Registry at ${source} is missing a "boilerplates" array.`)
  }
  return parsed as Registry
}

function looksLikeUrl(s: string) {
  return /^https?:\/\//i.test(s)
}
